name: Build
#
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16          
      - run: npm install
      - run: npm run build
      - run: |
          echo @hirenrparghi:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
          ls -la
          cd build
          ls -la
          cat .npmrc
      - run: npm adduser    
      - run: npm publish
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Clean Workspace
        if: always()
        run: |
         ls -la
         rm -rf ./* ./.[^.] ./.??*
         ls -la       
