name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build          
      - run: npm publish

          
      - name: Clean Workspace
        if: always()
        run: |
         ls -la
         rm -rf ./* ./.[^.] ./.??*
         ls -la       
