name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm install
          npm run build
      - run: |
          zip Modules.zip ./* -r
          ls
          pwd
      - name: Extract package
        run: |
          mkdir Modules
          unzip -o Modules.zip -d Modules
      - name: publish
        run: |        
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          cd Modules
          pwd
          ls -la
          npm publish --registy=https://npm.pkg.github.com

#       - name: publish
#         uses: 
#         with:
#           registry-url: https://npm.pkg.github.com
#           scope: '@hirenrparghi'
#       - name: npm publish
#         run: |
#           npm publish ${{ secrets.ACCESS_TOKEN }}
#           pwd
#           ls -la 
#           LATEST=`npm view . version`
#           CURRENT=`cat package.json | jq -r .version`
#           if [ "$LATEST" != "$CURRENT" ]
#           then

#             npm publish
#           fi
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: download published package
        run: |
          npm config set @hirenrparghi:registry https://npm.pkg.github.com
          npm i @hirenrparghi/package-example@2.4.5   
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      - name: check package
        run : |
          pwd
          ls -la
      - name: Clean Workspace
        if: always()
        run: |
         ls -la
         rm -rf ./* ./.[^.] ./.??*
         ls -la       
